# Generated by Django 4.0.2 on 2022-05-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('last_name', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=36)),
                ('phone', models.BigIntegerField()),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
